=== MHDante/ghostCatcherAndroid/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.mhdante.com"
    xmlns="http://www.mhdante.com" elementFormDefault="qualified">

    <xs:element name="chapter">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="chars">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="character" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="bio" type="xs:string" />
                                        <xs:element name="pose" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="id" type="xs:string" />
                                                <xs:attribute name="image" type="xs:string" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" />
                                    <xs:attribute name="name" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="locs">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="location" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="id" type="xs:string" />
                                            <xs:attribute name="name" type="xs:string" />
                                            <xs:attribute name="lat" type="xs:decimal" />
                                            <xs:attribute name="long" type="xs:decimal" />
                                            <xs:attribute name="tagline" type="xs:string" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="timeline">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="seq_pt" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="mysteries">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="mystery"
                                                        maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="solved"
                                                                    type="xs:string" />
                                                                <xs:element name="unsolved"
                                                                    type="xs:string" />
                                                            </xs:all>
                                                            <xs:attribute name="id"
                                                                type="xs:string" />
                                                            <xs:attribute name="solved"
                                                                type="xs:boolean" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="tasks">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="task" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute name="id"
                                                                        type="xs:string" />
                                                                    <xs:attribute name="enabled"
                                                                        type="xs:boolean" />
                                                                    <xs:attribute name="visible"
                                                                        type="xs:boolean" />
                                                                    <xs:attribute name="completed"
                                                                        type="xs:boolean" />
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="triggers">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="trigger"
                                                        maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="action"
                                                                    maxOccurs="unbounded">
                                                                    <xs:complexType>
                                                                        <xs:simpleContent>
                                                                            <xs:extension
                                                                                base="xs:string">
                                                                                <xs:attribute
                                                                                    name="type">
                                                                                    <xs:simpleType>
                                                                                        <xs:restriction
                                                                                            base="xs:string">
                                                                                            <xs:enumeration
                                                                                                value="DIALOG" />
                                                                                            <xs:enumeration
                                                                                                value="ENABLE_TOOL" />
                                                                                            <xs:enumeration
                                                                                                value="DISABLE_TOOL" />
                                                                                            <xs:enumeration
                                                                                                value="END_SQPT" />
                                                                                            <xs:enumeration
                                                                                                value="ENABLE_TRIGGER" />
                                                                                            <xs:enumeration
                                                                                                value="COMPLETE_TASK" />
                                                                                            <xs:enumeration
                                                                                                value="CHECK_TASK" />
                                                                                            <xs:enumeration
                                                                                                value="ACHIEVEMENT" />
                                                                                            <xs:enumeration
                                                                                                value="CONSUME_TRIGGER" />
                                                                                        </xs:restriction>
                                                                                    </xs:simpleType>
                                                                                </xs:attribute>
                                                                                <xs:attribute
                                                                                    name="lock"
                                                                                    type="xs:boolean" />
                                                                            </xs:extension>
                                                                        </xs:simpleContent>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                            <xs:attribute name="id"
                                                                type="xs:string" />
                                                            <xs:attribute name="type">
                                                                <xs:simpleType>
                                                                    <xs:restriction
                                                                        base="xs:string">
                                                                        <xs:enumeration
                                                                            value="AUTO" />
                                                                        <xs:enumeration
                                                                            value="TOOL_SUCCESS" />
                                                                        <xs:enumeration
                                                                            value="TOOL_FAILURE" />
                                                                        <xs:enumeration
                                                                            value="LOCATION_ENTER" />
                                                                        <xs:enumeration
                                                                            value="LOCATION_EXIT" />
                                                                        <xs:enumeration
                                                                            value="SCRIPTED" />
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                            </xs:attribute>
                                                            <xs:attribute name="data"
                                                                type="xs:string" />
                                                            <xs:attribute name="enabled"
                                                                type="xs:boolean" />
                                                            <xs:attribute name="timelimit"
                                                                type="xs:string" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:all>
                                    <xs:attribute name="id" type="xs:integer" />
                                    <xs:attribute name="name" type="xs:string" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== MHDante/ghostCatcherAndroid/experience_data/ghostcatcher/Exp1Chapter1.xml
<?xml version="1.0" encoding="utf-8"?>
<chapter xmlns="http://www.mhdante.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mhdante.com https://raw.githubusercontent.com/MHDante/ghostCatcherAndroid/master/schema.xsd">
  <chars>
    <character id="char1" name="Professor Wolfe">
      <bio>Professor Wolfe introduced himself when I inadvertently downloaded this Ghost Catcher app.  He's an overconfident yet distraught. He seems intent on catching ghosts, whatever the consequence....</bio>
      <pose id="pose0" image="pose0.png" />
      <pose id="pose1" image="pose1.png" />
      <pose id="pose2" image="pose2.png" />
      <pose id="pose3" image="pose3.png" />
      <pose id="pose4" image="pose4.png" />
      <pose id="pose5" image="pose5.png" />
      <pose id="pose6" image="pose6.png" />
      <pose id="pose7" image="pose7.png" />
      <pose id="pose8" image="pose8.png" />
      <pose id="pose9" image="pose9.png" />
      <pose id="pose10" image="pose10.png" />
      <pose id="pose11" image="pose11.png" />
      <pose id="pose12" image="pose12.png" />
      <pose id="pose13" image="pose13.png" />
      <pose id="pose14" image="pose14.png" />
      <pose id="pose15" image="pose15.png" />
      <pose id="pose16" image="pose16.png" />
      <pose id="pose17" image="pose17.png" />
      <pose id="pose18" image="pose18.png" />
      <pose id="pose19" image="pose19.png" />
      <pose id="pose20" image="pose20.png" />
      <pose id="pose21" image="pose21.png" />
    </character>
  </chars>
  <locs>
    <location id="loc1" name="RCC – Church and Gould" lat="43.65827" long="-79.37772" tagline="" />
    <location id="loc2" name="Lake Devo" lat="43.65769" long="-79.37981" tagline="" />
    <location id="loc3" name="Ram in the Rye" lat="43.65783" long="-79.37775" tagline="" />
  </locs>
  <timeline>
    <seq_pt id="01" name="Introduction">
      <triggers>
        <trigger id="00" type="AUTO" data="" enabled="true" timelimit="">
          <action type="DIALOG" lock="true">intro</action>
          <action type="ENABLE_TOOL" lock="false">locationmap</action>
		  <action type="ENABLE_TOOL" lock="false">rfdetector</action>
          <action type="ENABLE_TRIGGER" lock="false">01</action>
		  <action type="DISABLE_TRIGGER" lock="false">00</action>
        </trigger>
        <trigger id="01" type="LOCATION_ENTER" data="loc1" enabled="false" timelimit="">
          <action type="DIALOG" lock="true">1</action>
          <action type="ENABLE_TRIGGER" lock="true">01</action>
		  <action type="DISABLE_TRIGGER" lock="false">00</action>
        </trigger>
                <trigger id="01" type="LOCATION_ENTER" data="loc2" enabled="false" timelimit="">
          <action type="DIALOG" lock="true">2</action>
          <action type="ENABLE_TRIGGER" lock="true">01</action>
		  <action type="DISABLE_TRIGGER" lock="false">00</action>
        </trigger>
                <trigger id="01" type="LOCATION_ENTER" data="loc3" enabled="false" timelimit="">
          <action type="DIALOG" lock="true">3</action>
          <action type="ENABLE_TRIGGER" lock="true">01</action>
		  <action type="DISABLE_TRIGGER" lock="false">00</action>
        </trigger>
      </triggers>
    </seq_pt>
  </timeline>
</chapter>
